streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
        '': [user/themes/zynthian, user/themes/hotdoy]
meta_theme: null
color_bg: '#FFFFFF'
color_fg: '#000000'
color_sc: '#c00127'
color_hl: '#000000'
color_hl_inverted: '#FFFFFF'
color_loader: '#FFFFFF'
site_logo: '<img src="/user/themes/zynthian/img/zynthian_logo_black_trans.png">'
color_nav_fg: '#000000'
color_nav_panel_bg: '#FFFFFF'
color_nav_panel_fg: '#000000'
org_name: Zynthian
google_tracking_id: null
tracking: '0'
google_maps_api_key: null
google_maps_snazzy: null
facebook_app_id: null
snipcart_api_key: null
price_prefix: null
price_suffix: null
lazyload: '1'
placeholder: '1'
links: dns-prefetch
reveal_content: '1'
org_logo:
  user/assets/hotdoy/organization/logo-schema.jpg:
    name: logo-schema.jpg
    type: image/jpeg
    size: 46941
    path: user/assets/hotdoy/organization/logo-schema.jpg
google_maps_icon: {  }
org_desc: '<p>An Open Platform for Sound Synthesis. Based on Raspberry Pi and Linux, its hardware specification is public and software is Open Source.</p>'
about_desc: "<h4>About Us</h4>\r\n<p>Zynthian software is developed by an open community of developers around the world.</p>\r\n<p>Official kits are designed and sold by zynthian's project founder, Fernando Moyano (@jofemodo).</p>"
policy_linkt: '<h4> About Us</h4>'
policy_link: /privacy
github_link: 'https://github.com/zynthian'
youtube_link: 'https://www.youtube.com/channel/UCc9Tv__HdwQjPjKUd5mIhaw'
twitter_link: 'https://twitter.com/zynthianbox'
instagram_link: 'https://www.instagram.com/zynthian/'
facebook_link: 'https://www.facebook.com/zynthianbox'
