streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
        '': [user/themes/zynthian, user/themes/hotdoy]
meta_theme: null
color_bg: '#FFFFFF'
color_fg: '#000000'
color_sc: '#c00127'
color_hl: '#000000'
color_hl_inverted: '#FFFFFF'
color_loader: '#FFFFFF'
site_logo: '<img src="/user/themes/zynthian/img/zynthian_logo_black_trans.png">'
color_nav_fg: '#000000'
color_nav_panel_bg: '#FFFFFF'
color_nav_panel_fg: '#000000'
org_name: Zynthian
google_tracking_id: null
tracking: '0'
google_maps_api_key: null
google_maps_snazzy: null
facebook_app_id: null
snipcart_api_key: null
price_prefix: null
price_suffix: null
lazyload: '1'
placeholder: '1'
links: dns-prefetch
reveal_content: '1'
favicon:
  user/assets/zynthian/favicon/favicon.png:
    name: favicon.png
    type: image/png
    size: 7126
    path: user/assets/zynthian/favicon/favicon.png
org_logo:
  user/assets/zynthian/organization/zynthian_logo.svg:
    name: zynthian_logo.svg
    type: image/svg+xml
    size: 7361
    path: user/assets/zynthian/favicon/zynthian_logo.svg
google_maps_icon: {  }
org_desc: '<p>An open Platform for Sound Synthesis & Processing.<br>Based on Raspberry Pi and Linux, its hardware specification is public and software is Open Source.</p>'
about_desc: "<h3>About Us</h3>\n<p>Zynthian hardware & software is developed and maintained by an open community of intrepid users & developers around the world. Official kits are designed and sold by zynthian project founders on the <a href='https://shop.zynthian.org'>Zynthian Shop</a>.</p>"
policy_linkt: '<h4> About Us</h4>'
policy_link: /privacy
github_link: 'https://github.com/zynthian'
youtube_link: 'https://www.youtube.com/channel/UCc9Tv__HdwQjPjKUd5mIhaw'
twitter_link: 'https://twitter.com/zynthianbox'
instagram_link: 'https://www.instagram.com/zynthian/'
facebook_link: 'https://www.facebook.com/zynthianbox'
