title: 'Zynthian: Open Synth Platform'
default_lang: en
author:
  name: 'Ganesha + Jofemodo'
  email: info@zynthian.org
taxonomies:
  - category
  - tag
  - menu
metadata:
  description: 'Zynthian is an Open Synth Platform based in Raspberry Pi, Linux and Open Source Synthesizers'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
