title: Zynthian
default_lang: en
author:
  name: 'Ganesha + Jofemodo'
  email: info@zynthian.org
taxonomies:
  - category
  - tag
metadata:
  description: 'Zynthian Website'
  # keywords: 'HTML, CSS, Grav, Theme, One Page'
  # robots: 'noindex, nofollow'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
